language: c++
script: make -f ${MAKEFILE} && make -f ${MAKEFILE} test
matrix:
  include:
    - os: osx
      env: MAKEFILE=Makefile
    - os: osx
      env: MAKEFILE=Makefile.xcode
    - os: linux
      # complicated due to <regex> support
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MAKEFILE=Makefile
        - CXX=g++-4.9
